library(sqlmlutils)
library(RODBCext)

cnnStr <- connectionInfo(server="localhost\\SQL2017")
print(cnnStr)
dbhandle <- odbcDriverConnect(cnnStr)
print(dbhandle)
res <- sqlQuery(dbhandle, "SELECT 1")
print(res)
odbcClose(dbhandle)
