library(sqlmlutils)
library(RODBCext)

Server <- Sys.getenv("SERVER")
cnnStr <- connectionInfo(server=Server, database="AirlineTestDB")
print(cnnStr)
dbhandle <- odbcDriverConnect(cnnStr)
print(dbhandle)
res <- sqlQuery(dbhandle, "SELECT 1")
print(res)
odbcClose(dbhandle)
