# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  R:
    #runs-on: [self-hosted, 1ES.Pool=sqlmlutils_GH_RunnerPool]
    strategy:
      matrix:
        include:
          - r-version: "3.5.2"
            sql-platform: "box"
          #- r-version: "4.2.0"
          #  sql-platform: "box"

    env:
      # Define CI to skip some test case.
      CI: True
      DATABASE: ${{ secrets.DATABASE }}

    defaults:
      run:
        shell: cmd

    steps:
      - name: Download CAB files
        run: Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2134897 -OutFile C:\
        shell: cmd
       
      - name: Install SQL Server 2019
        run: choco install sql-server-2019-cumulative-update -y -params "'/MRCACHEDIRECTORY=`"C:\`"" /ACTION=Install /FEATURES=SQLEngine,ADVANCEDANALYTICS /INSTANCENAME=MSSQLSERVER /SQLSYSADMINACCOUNTS=`"Administrator`" /IACCEPTSQLSERVERLICENSETERMS'""
        shell: cmd

      - name: Install sqlcmd
        run: choco install sqlcmd
        shell: cmd
