name: Python 3.10 Sandbox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  SQLServer2022:
    runs-on: windows-2022
    
    env:
      # Define CI to skip some test case.
      CI: True
      python-version: "3.10.2"

    defaults:
      run:
        shell: cmd

    steps:
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Verify Python installation
        run: python --version && where python && echo %PYTHON%
        shell: cmd

      - name: Checkout Branch
        uses: actions/checkout@v2
        run: dir

      #- name: Install revoscalepy and dependencies
      #  run: |
      #    cd C:\MLS\Python
      #    python -m pip install -t "C:\MLS\Python\Lib\site-packages" dill numpy==1.22.0 pandas patsy python-dateutil
      #    python -m pip install -t "C:\MLS\Python\Lib\site-packages" https://aka.ms/sqlml/python3.10/windows/revoscalepy-10.0.1-py3-none-any.whl

      #- name: Grant READ/EXECUTE access to installed libraries
      #  run: |
      #    icacls "C:\MLS\Python\Lib\site-packages" /grant "NT Service\MSSQLLAUNCHPAD":(OI)(CI)RX /T
      #    icacls "C:\MLS\Python\Lib\site-packages" /grant *S-1-15-2-1:(OI)(CI)RX /T

      - name: Install Python dependencies
        working-directory: ${{ env.Python3_ROOT_DIR }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt

      - name: Build Python Package
        working-directory: ${{ env.Python3_ROOT_DIR }}
        run: ./buildandinstall.cmd
