# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PASSWORD_AIRLINE_USER: ${{ secrets.PASSWORD_AIRLINE_USER }}
  PASSWORD_AIRLINE_USER_DBOWNER: ${{ secrets.PASSWORD_AIRLINE_USER_DBOWNER }}
  DRIVER: "{ODBC Driver 17 for SQL Server}"

jobs:
  R:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - r-version: "3.5.2"
            sql-platform: "box"
          #- r-version: "4.2.0"
          #  sql-platform: "box"

    env:
      # Define CI to skip some test case.
      CI: True
      DATABASE: ${{ secrets.DATABASE }}

    defaults:
      run:
        shell: cmd

    steps:

      - name: Generate password
        run: |
          setlocal enabledelayedexpansion
          set password=%random%%random%%random%qaZ~@
          echo dbPassword=!password! >> %GITHUB_ENV%

      - name: Download Microsoft R Open cabinet file
        run: |
          set CurrentDir=%cd%
          curl -L https://go.microsoft.com/fwlink/?linkid=2085686 -o "%CurrentDir%/SRO_3.5.2.125_1033.cab"
        shell: cmd
      
      - name: Download Microsoft Python Open cabinet file
        run: |
          set CurrentDir=%cd%
          curl -L https://go.microsoft.com/fwlink/?linkid=2085793 -o "%CurrentDir%/SPO_4.5.12.120_1033.cab"
        shell: cmd

      # /MRCACHEDIRECTORY=`"C:\Temp`"
      # /SQLSYSADMINACCOUNTS=SA
      - name: Install SQL Server 2019
        run: | 
          set CurrentDir=%cd%
          choco install sql-server-2019 -y -params "'/MRCACHEDIRECTORY=%CurrentDir% /SAPWD=%dbPassword% /SECURITYMODE=SQL /TCPENABLED=1 /INDICATEPROGRESS /ACTION=Install /FEATURES=SQLEngine,ADVANCEDANALYTICS /INSTANCENAME=MSSQLSERVER /IACCEPTSQLSERVERLICENSETERMS'"
        shell: cmd

      - name: Save Logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Chocolatey Logs
          path: C:\ProgramData\chocolatey\logs\chocolatey.log
          retention-days: 20
      
      - name: Apply SQL Server 2019 Cumulative Update
        run: choco install sql-server-2019-cumulative-update -y
        shell: cmd

      - name: Install sqlcmd
        run: choco install sqlcmd
        shell: cmd

      - name: Check Connectivity to SQL Database
        run: |
          sqlcmd -S localhost -U SA -P %dbPassword% -d Master -l 5 -Q "SELECT @@VERSION"
        shell: cmd

      - name: Enable External Scripts
        run: sqlcmd -S localhost -Q "EXEC sp_configure  'external scripts enabled', 1 \n RECONFIGURE WITH OVERRIDE"

      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Set up R ${{ matrix.r-version }} Runtime
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install R Package Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          working-directory: ./R
          extra-packages:
            #Retrieves most recent odbc pkg from cran to avoid errors seen in older versions.
            #Updated odbc pkg is still compatible with R >= 3.2.0
            cran::odbc
            cran::xml2
            rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./R
